version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data   # SQLite DB folder
      - ./backend:/app/backend  # Backend code
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend